<?php
/**
 * CreateReplenishmentRequest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  BolApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * v6
 *
 * The bol.com API for Retailers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BolApi\Client\Model;

use \ArrayAccess;
use \BolApi\Client\ObjectSerializer;

/**
 * CreateReplenishmentRequest Class Doc Comment
 *
 * @category Class
 * @package  BolApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class CreateReplenishmentRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateReplenishmentRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'reference' => 'string',
        'delivery_info' => '\BolApi\Client\Model\CreateDeliveryInfo',
        'labeling_by_bol' => 'bool',
        'number_of_load_carriers' => 'int',
        'pickup_appointment' => '\BolApi\Client\Model\CreatePickupAppointment',
        'lines' => '\BolApi\Client\Model\CreateReplenishmentLine[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'reference' => null,
        'delivery_info' => null,
        'labeling_by_bol' => null,
        'number_of_load_carriers' => 'int32',
        'pickup_appointment' => null,
        'lines' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'reference' => 'reference',
        'delivery_info' => 'deliveryInfo',
        'labeling_by_bol' => 'labelingByBol',
        'number_of_load_carriers' => 'numberOfLoadCarriers',
        'pickup_appointment' => 'pickupAppointment',
        'lines' => 'lines'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'reference' => 'setReference',
        'delivery_info' => 'setDeliveryInfo',
        'labeling_by_bol' => 'setLabelingByBol',
        'number_of_load_carriers' => 'setNumberOfLoadCarriers',
        'pickup_appointment' => 'setPickupAppointment',
        'lines' => 'setLines'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'reference' => 'getReference',
        'delivery_info' => 'getDeliveryInfo',
        'labeling_by_bol' => 'getLabelingByBol',
        'number_of_load_carriers' => 'getNumberOfLoadCarriers',
        'pickup_appointment' => 'getPickupAppointment',
        'lines' => 'getLines'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['reference'] = $data['reference'] ?? null;
        $this->container['delivery_info'] = $data['delivery_info'] ?? null;
        $this->container['labeling_by_bol'] = $data['labeling_by_bol'] ?? null;
        $this->container['number_of_load_carriers'] = $data['number_of_load_carriers'] ?? null;
        $this->container['pickup_appointment'] = $data['pickup_appointment'] ?? null;
        $this->container['lines'] = $data['lines'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['reference'] === null) {
            $invalidProperties[] = "'reference' can't be null";
        }
        if ($this->container['labeling_by_bol'] === null) {
            $invalidProperties[] = "'labeling_by_bol' can't be null";
        }
        if ($this->container['number_of_load_carriers'] === null) {
            $invalidProperties[] = "'number_of_load_carriers' can't be null";
        }
        if (($this->container['number_of_load_carriers'] > 20)) {
            $invalidProperties[] = "invalid value for 'number_of_load_carriers', must be smaller than or equal to 20.";
        }

        if (($this->container['number_of_load_carriers'] < 1)) {
            $invalidProperties[] = "invalid value for 'number_of_load_carriers', must be bigger than or equal to 1.";
        }

        if ($this->container['lines'] === null) {
            $invalidProperties[] = "'lines' can't be null";
        }
        if ((count($this->container['lines']) > 9999)) {
            $invalidProperties[] = "invalid value for 'lines', number of items must be less than or equal to 9999.";
        }

        if ((count($this->container['lines']) < 1)) {
            $invalidProperties[] = "invalid value for 'lines', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets reference
     *
     * @return string
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string $reference Custom user reference for this replenishment. Must contain at least 1 digit and only upper case characters allowed.
     *
     * @return self
     */
    public function setReference($reference)
    {
        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets delivery_info
     *
     * @return \BolApi\Client\Model\CreateDeliveryInfo|null
     */
    public function getDeliveryInfo()
    {
        return $this->container['delivery_info'];
    }

    /**
     * Sets delivery_info
     *
     * @param \BolApi\Client\Model\CreateDeliveryInfo|null $delivery_info delivery_info
     *
     * @return self
     */
    public function setDeliveryInfo($delivery_info)
    {
        $this->container['delivery_info'] = $delivery_info;

        return $this;
    }

    /**
     * Gets labeling_by_bol
     *
     * @return bool
     */
    public function getLabelingByBol()
    {
        return $this->container['labeling_by_bol'];
    }

    /**
     * Sets labeling_by_bol
     *
     * @param bool $labeling_by_bol Indicates whether the replenishment will be labeled by bol.com or not.
     *
     * @return self
     */
    public function setLabelingByBol($labeling_by_bol)
    {
        $this->container['labeling_by_bol'] = $labeling_by_bol;

        return $this;
    }

    /**
     * Gets number_of_load_carriers
     *
     * @return int
     */
    public function getNumberOfLoadCarriers()
    {
        return $this->container['number_of_load_carriers'];
    }

    /**
     * Sets number_of_load_carriers
     *
     * @param int $number_of_load_carriers The number of parcels in this replenishment.
     *
     * @return self
     */
    public function setNumberOfLoadCarriers($number_of_load_carriers)
    {

        if (($number_of_load_carriers > 20)) {
            throw new \InvalidArgumentException('invalid value for $number_of_load_carriers when calling CreateReplenishmentRequest., must be smaller than or equal to 20.');
        }
        if (($number_of_load_carriers < 1)) {
            throw new \InvalidArgumentException('invalid value for $number_of_load_carriers when calling CreateReplenishmentRequest., must be bigger than or equal to 1.');
        }

        $this->container['number_of_load_carriers'] = $number_of_load_carriers;

        return $this;
    }

    /**
     * Gets pickup_appointment
     *
     * @return \BolApi\Client\Model\CreatePickupAppointment|null
     */
    public function getPickupAppointment()
    {
        return $this->container['pickup_appointment'];
    }

    /**
     * Sets pickup_appointment
     *
     * @param \BolApi\Client\Model\CreatePickupAppointment|null $pickup_appointment pickup_appointment
     *
     * @return self
     */
    public function setPickupAppointment($pickup_appointment)
    {
        $this->container['pickup_appointment'] = $pickup_appointment;

        return $this;
    }

    /**
     * Gets lines
     *
     * @return \BolApi\Client\Model\CreateReplenishmentLine[]
     */
    public function getLines()
    {
        return $this->container['lines'];
    }

    /**
     * Sets lines
     *
     * @param \BolApi\Client\Model\CreateReplenishmentLine[] $lines lines
     *
     * @return self
     */
    public function setLines($lines)
    {

        if ((count($lines) > 9999)) {
            throw new \InvalidArgumentException('invalid value for $lines when calling CreateReplenishmentRequest., number of items must be less than or equal to 9999.');
        }
        if ((count($lines) < 1)) {
            throw new \InvalidArgumentException('invalid length for $lines when calling CreateReplenishmentRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['lines'] = $lines;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


