<?php
/**
 * BulkProcessStatusRequestTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  BolApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * v5
 *
 * The bol.com API for Retailers.
 *
 * The version of the OpenAPI document: 5.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BolApi\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BulkProcessStatusRequestTest Class Doc Comment
 *
 * @category    Class
 * @description BulkProcessStatusRequest
 * @package     BolApi\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BulkProcessStatusRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BulkProcessStatusRequest"
     */
    public function testBulkProcessStatusRequest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "process_status_queries"
     */
    public function testPropertyProcessStatusQueries()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
