<?php
/**
 * DeliveryOptionTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  BolApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * v4
 *
 * The bol.com API for Retailers.
 *
 * The version of the OpenAPI document: 4.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BolApi\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DeliveryOptionTest Class Doc Comment
 *
 * @category    Class
 * @description A delivery option shows how and the costs of a transport for a shippable configuration
 * @package     BolApi\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DeliveryOptionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DeliveryOption"
     */
    public function testDeliveryOption()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shipping_label_offer_id"
     */
    public function testPropertyShippingLabelOfferId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valid_until_date"
     */
    public function testPropertyValidUntilDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "transporter_code"
     */
    public function testPropertyTransporterCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "label_type"
     */
    public function testPropertyLabelType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "label_price"
     */
    public function testPropertyLabelPrice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "package_restrictions"
     */
    public function testPropertyPackageRestrictions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "handover_details"
     */
    public function testPropertyHandoverDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
