<?php
/**
 * LoadCarrierTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  BolApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * v7 - Retailer API
 *
 * The bol.com API for retailers.
 *
 * The version of the OpenAPI document: 7.x
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BolApi\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * LoadCarrierTest Class Doc Comment
 *
 * @category    Class
 * @description LoadCarrier
 * @package     BolApi\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LoadCarrierTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LoadCarrier"
     */
    public function testLoadCarrier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sscc"
     */
    public function testPropertySscc()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "transport_label_track_and_trace"
     */
    public function testPropertyTransportLabelTrackAndTrace()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "transport_state"
     */
    public function testPropertyTransportState()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "transport_state_update_date_time"
     */
    public function testPropertyTransportStateUpdateDateTime()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
