<?php
/**
 * CommissionsApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  BolApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * v7 - Retailer API
 *
 * The bol.com API for retailers.
 *
 * The version of the OpenAPI document: 7.x
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BolApi\Client\Test\Api;

use \BolApi\Client\Configuration;
use \BolApi\Client\ApiException;
use \BolApi\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CommissionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  BolApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CommissionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCommission
     *
     * Get all commissions and reductions by EAN per single EAN.
     *
     */
    public function testGetCommission()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCommissions
     *
     * Get all commissions and reductions by EAN in bulk.
     *
     */
    public function testGetCommissions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
