<?php
/**
 * SubscriptionsApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  BolApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * v6
 *
 * The bol.com API for Retailers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BolApi\Client\Test\Api;

use \BolApi\Client\Configuration;
use \BolApi\Client\ApiException;
use \BolApi\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SubscriptionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  BolApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SubscriptionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deletePushNotificationSubscription
     *
     * Delete push notification subscription.
     *
     */
    public function testDeletePushNotificationSubscription()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPushNotificationSubscription
     *
     * Get push notification subscription by id.
     *
     */
    public function testGetPushNotificationSubscription()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPushNotificationSubscriptions
     *
     * Get push notification subscriptions.
     *
     */
    public function testGetPushNotificationSubscriptions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSubscriptionKeys
     *
     * Retrieve public keys for push notification signature validation..
     *
     */
    public function testGetSubscriptionKeys()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postPushNotificationSubscription
     *
     * Create push notification subscription.
     *
     */
    public function testPostPushNotificationSubscription()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postTestPushNotification
     *
     * Send test push notification for subscriptions.
     *
     */
    public function testPostTestPushNotification()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putPushNotificationSubscription
     *
     * Update push notification subscription.
     *
     */
    public function testPutPushNotificationSubscription()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
